### PR TITLE
Adding Beamer - presentation maker inside LaTex environment

### PR DESCRIPTION
**Pull request by haotruongnhat**
Please refer to **Beamer Presentation** in README.md

### CODE REVIEW

**Comment by haotruongnhat** [comment]
@PIX3LFLUX, please review and comment on this presentation demo ([Demo pdf](https://github.com/PIX3LFLUX/HSK-Latex-Skript-Template/blob/a6df00fbc32d529e73fbbf3a16f687a4a711c77f/Demo/02_presentation.pdf)) to see whether I could work further.

There are several differences compared to ppt template due to the restrictions of beamer (or I haven't figured out yet):
- Content text size could only be set globally at 17pt. In ppt, it is 18pt.
- The used font is Carlito. In ppt, it is Calibri.
- Missing and unfinished templates: table, equation, footnote, cite, figure.

**Comment by PIX3LFLUX** [comment]
Tested the beamer template with TeXstudio on MacOS using a direct clone from Github. 

The beamer template using 02_presentation.tex doesn't build. It seems that a "Templates" folder is missing.
Please see the log output:

````
Package pdftex.def Error: File `Templates/HKA-Opening.pdf' not found: using draft setting. \EITCoverVI{Wilkommen}{Vorname Nachname}
Package pdftex.def Error: File `Templates/HKA_Opening_KA_text.pdf' not found: using draft setting. \EITCoverVI{Wilkommen}{Vorname Nachname}
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. \EITCoverVI{Wilkommen}{Vorname Nachname}
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. \EITTableOfContent{Inhaltsverzeichnis}{2}
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. \EITTableOfContent{Inhaltsverzeichnis}{2}
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA_Slide_KA_text.pdf' not found: using draft setting. }
Package pdftex.def Error: File `Templates/HKA-Normal.pdf' not found: using draft setting. }
'babel/polyglossia' detected but 'csquotes' missing.
No file 02_presentation.bbl.
File `Templates/HKA-Opening.pdf' not found
File `Templates/HKA_Opening_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
Citation 'article_key' on page 24 undefined
Citation 'book_key' on page 24 undefined
File `Templates/HKA_Slide_KA_text.pdf' not found
File `Templates/HKA-Normal.pdf' not found
There were undefined references.
Label(s) may have changed. Rerun to get cross-references right.
Please (re)run Biber on the file:(biblatex) 02_presentation(biblatex) and rerun LaTeX afterwards.
```

**Comment by PIX3LFLUX** [comment]
There are 9 slides "EIT Präsentation mit Liste" now :-)
The table design could follow [this](https://tex.stackexchange.com/questions/604496/how-to-generate-beautiful-tables-in-latex)

**Comment by haotruongnhat** [comment]
Added `Templates` folder for H-KA text background. You could have a try.

**Comment by PIX3LFLUX** [comment]
> 

Thanks it works now!

**Comment by haotruongnhat** [comment]
The 9 slides of "EIT Präsentation mit Liste" could be removed by remove this `[<+->]` or `[<+- | alert@+>]` in `\begin{itemize}`. Just want to show off some functions of beamer :-)

I will modify the table later.

**Comment by haotruongnhat** [comment]
Updated on table. 
Added some example slides, and [cheatsheet](https://github.com/PIX3LFLUX/HSK-Latex-Skript-Template/blob/a9c01937042afaee9650130cdeb3c1eadc7737fc/Demo/presentation_cheatsheet.pdf).

Demo: [PDF](https://github.com/PIX3LFLUX/HSK-Latex-Skript-Template/blob/a9c01937042afaee9650130cdeb3c1eadc7737fc/Demo/02_presentation.pdf)

**Pull request merged**
